### ISSUE TITLE
400 - Insufficient developer role

### ISSUE THREAD

**Issue by bengreenbank** [wearealloy/craft3-instagramFeed#1]
Hey,

I am trying to get a new access code for my Instagram account, as the old one expired. However I now get a 400 error.

```
error_type | "OAuthException"
code | 400
error_message | "Insufficient developer role"
```

Also, I end up on this page https://www.instagram.com/oauth/authorize, rather than the return URL for my website.

Any help as to why this error might be occuring would be appreciated. Thanks.

**Comment by gracehcoote** [comment]
Hi, I'm currently experiencing this issue myself. I believe the problem is that you need to add and authorise a test user, if you go to this page: [https://developers.facebook.com/docs/instagram-basic-display-api/getting-started](url) and then go to step 3 onwards, there is more information about it. The problem for me is that I'm doing this for a client's website so I have to wait on them to do any of this stage!

**Comment by wearealloy** [comment]
Hello @bengreenbank ,

Sorry I'm getting to the issue this late. To get a new access token after the old one has expired what you need to do is click on the "get auth link" button again. This would take you to [ https://www.instagram.com/oauth/authorize](https://www.instagram.com/oauth/authorize) where you have to log in to the linked instagram account to give permissions again to the app in order to work. After you have given the app permissions by just following the prompts, you will ve redirected to your website, here the url should contain the new API Token which you have to put in the plugin settings, after that just save the plugin settings and it should be working again. 

As of @gracehcoote comment. The only way right now to get a token is by having access to that Facebook and Instagram accounts. So yes, if you don't have access, you will have to wait for your client to do all this which is a pain. The other way is by creating the projects under you facebook account and having the client as an instagram tester on that app, is not ideal but it works so you might want to do that so the at least the client does not need to do the facebook part.

I will update de plugin so the redirect URI can be the one that takes you to the plugins settings and automatically copies and pastes the API code into the settings. This should make it a lot more seamless.
